### ISSUE TITLE
How to ensure Edge Router (X) startup script connects to Tailscale with certain parameters?

### ISSUE THREAD

**Issue by yabdali** [jamesog/tailscale-edgeos#13]
Hi,
I would appreciate if you can provide some insights about how to ensure that Edge Router X connects to Tailscale network with certain parameters.  E.g, below I use my ER-X to connect to a tailscale which has another node advertising its routes, I want clients connected to ER-X to be able to connect to other clients behind the other node.  At the same time, I want clients behind the other node to be able to connect to clients behind ER-X.  I have tested the line below and it works well.  How to ensure this would be persisted across reboots?
`sudo tailscale up --accept-routes --advertise-routes=10.10.0.0/24`

**Comment by jamesog** [comment]
Hi @yabdali, the state is persisted to the flash drive so it should come up with the same parameters and device key at boot. Is that not happening for you?

**Comment by yabdali** [comment]
> Hi @yabdali, the state is persisted to the flash drive so it should come up with the same parameters and device key at boot. Is that not happening for you?

Thanks, indeed it save the parameters after I rebooted.  I had a different experience with my NAS where I had to create a startup script to add custom parameters.  Thanks for your prompt response.
