### ISSUE TITLE
Please add tailscale upgrade instructions

### ISSUE THREAD

**Issue by Strider3000** [jamesog/tailscale-edgeos#2]
Love this guide. I've used it on three units without a hitch.
Please add instructions for updating the tailscale service to the latest version (as updated become available).

**Comment by jamesog** [comment]
That's a good call.

I need to check if the Debian repo they host has ARM packages, which will make it easier than the binary download we do now. From the [download page](https://tailscale.com/download/linux/debian-stretch) it does say they have packages for ARM 32-bit and 64-bit so hopefully that'll work.

**Comment by jamesog** [comment]
I've just tested using the Debian repo and it works great on my ERL. I'll try on the ER4 later, but I think that should work fine. This means upgrading should be a simple `sudo apt-get upgrade`.

I'll try and figure out the right modifications to the instructions but it's quite straightforward. Via #1 I'm also investigating tailscaled not properly reconnecting after reboot so I'll coordinate updating the instructions with both of these tickets.

**Comment by jamesog** [comment]
Very quick notes on setting up the Debian repo:

```
configure
set system package repository tailscale url https://pkgs.tailscale.com/stable/debian
set system package repository tailscale distribution stretch
set system package repository tailscale components main
commit
sudo bash
curl -fsSL https://pkgs.tailscale.com/stable/debian/stretch.gpg | apt-key add -
exit
sudo apt-get update
sudo apt-get install tailscale
```

**Comment by rburgst** [comment]
should the readme then be updated to use the debian distribution instead? Wondering whether I should change since I have set my ERX up using the instructions in README.

**Comment by jamesog** [comment]
I have a branch which has a rough cut of that method, if you'd like to try it out: https://github.com/jamesog/tailscale-edgeos/tree/package-repo

I haven't had a lot of free time to fully test it, hence it's not in the main branch yet.

**Comment by esolitos** [comment]
@jamesog Thanks for the great guide and scripts!

In the README present in the `package-repo` branch you refer to a script: `/config/scripts/post-config.d/tailscale.sh`
However this script doesn't seem to be anywhere in your repo, what should this file contain?

**Comment by jamesog** [comment]
@esolitos this is generated by the firstboot script: https://github.com/jamesog/tailscale-edgeos/commit/edee1367d0b4b91d29460ca78ee0ab0e348f9bb5#diff-be787cd2908ede311fdeb2dbe14d2c12b7cc24224d5ccf95712d94d7c5b7e852

Thanks for testing the package-repo branch!

**Comment by esolitos** [comment]
Ah! I see, I did not notice you updated the firstboot script so following the guide I downloaded the "old" file from the `main` branch. :) 

Downloaded now the new one and all works out. 👍🏼 
Already setup 2 edgerouter x with your giude, all seems to be ok.

*But worry not:* I will come here and scream very loudly if everything breaks at the first upgrade, considering the 2 routers are 3000km apart. 😆

**Comment by jamesog** [comment]
It's been a long time (sorry about that!) but I've finally sorted out a proper process for using the package repo as of cb7f10c760e5f10187970a09312658cb28ec8726. There's a note on how to upgrade near the bottom.

I haven't written up a migration guide for moving from the old manual method but hopefully people can figure it out. The new process is mostly automated 🎉 .

**Comment by esolitos** [comment]
Thank you again, no worries about the delay, the final result seems really solid. :)
