### ISSUE TITLE
Seems stuck on 1.36.2

### ISSUE THREAD

**Issue by muzicman0** [jamesog/tailscale-edgeos#22]
There has been a security update to Tailsscale (1.38.4), but when I do an 'apt install tailscale' it says the latest version is installed (1.36.2).

Is there a way to update to the latest?

**Comment by jamesog** [comment]
Did you `apt-get update` first? If you did and it doesn't show a new version you should talk to Tailscale directly.

**Comment by muzicman0** [comment]
Yes I did.

**Comment by jamesog** [comment]
You'll need to talk to Tailscale then. It likely means the repo isn't updated.

**Comment by LeonFedotov** [comment]
@muzicman0 im also wondering, did you end up figuring this out?
@jamesog what arch/binary is this using can i manually compile and stick it in?

**Comment by jamesog** [comment]
`uname -a` will tell you which arch your particular router is running. My ER4 is mips64. Yes you could compile it yourself, or grab a pre-built binary tarball https://pkgs.tailscale.com/stable/#static. If you check the commit history on this repo it originally used the tarballs but I switched it to use the repo as it's generally easier.

**Comment by LeonFedotov** [comment]
@jamesog thank you for the info
what i did was download the mips binaries(mine were mipsle) and manually replacing them on the router which worked. 
im still puzzled on to why this package is missing in the repo or maybe its my router that doesnt actually update its records ?

**Comment by jamesog** [comment]
It's the same for me. Like I said before, someone should open an issue with Tailscale to get the repo updated.

**Comment by muzicman0** [comment]
So I replaced the tailscale and tailscaled binary.  It seems to be working.  I assume there is no value in 'Systemd' folder since it was already installed.

**Comment by jamesog** [comment]
Cross-referencing related Tailscale issue: tailscale/tailscale#8005

A friend over at Tailscale has a fix incoming.

**Comment by jamesog** [comment]
The repo now has 1.40.1, however note that it now installs an extra `tailscale-archive-keyring` package:

```
jamesog@gw02:~$ sudo apt-get install tailscale
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  tailscale-archive-keyring
The following NEW packages will be installed:
  tailscale-archive-keyring
The following packages will be upgraded:
  tailscale
1 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 22.0 MB of archives.
After this operation, 2146 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 https://pkgs.tailscale.com/stable/debian stretch/main mips tailscale mips 1.40.1 [22.0 MB]
Get:2 https://pkgs.tailscale.com/stable/debian stretch/main all tailscale-archive-keyring all 1.35.181 [3082 B]
Fetched 22.0 MB in 5s (3925 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 37066 files and directories currently installed.)
Preparing to unpack .../tailscale_1.40.1_mips.deb ...
Unpacking tailscale (1.40.1) over (1.36.2) ...
Selecting previously unselected package tailscale-archive-keyring.
Preparing to unpack .../tailscale-archive-keyring_1.35.181_all.deb ...
Unpacking tailscale-archive-keyring (1.35.181) ...
Setting up tailscale (1.40.1) ...
Setting up tailscale-archive-keyring (1.35.181) ...

jamesog@gw02:~$ dpkg -L tailscale-archive-keyring
/usr
/usr/share
/usr/share/keyrings
/usr/share/keyrings/tailscale-archive-keyring.gpg
```

This is very useful! But I'll need to incorporate this into the instructions.
