### ISSUE TITLE
Feature Wizard

### ISSUE THREAD

**Issue by tobyg0** [jamesog/tailscale-edgeos#23]
Could this be turned into a feature wizards so that it you could do a basic configuration in the GUI?

**Comment by jamesog** [comment]
That would involve having to modify core parts of EdgeOS, which I'm not willing to do. This isn't really aimed at novices.

**Comment by tobyg0** [comment]
I've installed and set this up on a couple of router so I wouldn't say I'm a novice, since Tailscale has updated their plan I was planning on installing this on >100 routers and being able to just use a wizard would of helped with that.

**Comment by jamesog** [comment]
If you're deploying that many devices you'd be better off with some kind of automation based on the approach in this guide, than manually clicking around GUI wizards.

**Comment by tobyg0** [comment]
True, it was more for having other people who are novices deploy it.
