### ISSUE TITLE
File not found when reading packages

### ISSUE THREAD

**Issue by advisorgee** [jamesog/tailscale-edgeos#38]
I have an EdgeRouter 6P v2.0.9-hotfix.7

When the post-config script runs there is a file not found on one of the packages and the installer fails:

Ign:3 http://http.us.debian.org/debian stretch/main all Packages
Err:4 http://http.us.debian.org/debian stretch/main mips Packages
  404  Not Found [IP: 64.50.233.100 80]
Ign:5 http://http.us.debian.org/debian stretch/main Translation-en
Ign:6 http://http.us.debian.org/debian stretch/contrib all Packages
Ign:7 http://http.us.debian.org/debian stretch/contrib mips Packages
Ign:8 http://http.us.debian.org/debian stretch/contrib Translation-en
Ign:10 http://http.us.debian.org/debian stretch/non-free all Packages
Ign:11 http://http.us.debian.org/debian stretch/non-free mips Packages
Ign:12 http://http.us.debian.org/debian stretch/non-free Translation-en
Fetched 6565 B in 2s (2334 B/s)
Reading package lists... Done
W: The repository 'http://http.us.debian.org/debian stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://http.us.debian.org/debian/dists/stretch/main/binary-mips/Packages  404  Not Found [IP: 64.50.233.100 80]
E: Some index files failed to download. They have been ignored, or old ones used instead

**Comment by jamesog** [comment]
Seems like Debian finally pulled Stretch from the main mirrors as it's pretty old. EdgeOS is based on Debian Stretch and they haven't updated it for a long time (since EdgeOS 2.0).

Switching `http.us.debian.org` for `archive.debian.org` in `/etc/apt/sources.list` should fix it. Give that a go.

**Comment by advisorgee** [comment]
That worked; except for me there was no sources.list file. There was a sources.list.d directory and a stretch.list file in there that I changed.
Thanks for the quick reply.
