### ISSUE TITLE
Guidance on overhead impact on EdgeOS device

### ISSUE THREAD

**Issue by mdav43** [jamesog/tailscale-edgeos#4]
Is there anyone that can give guidance on the impact of router performance with the additional overhead of running tailscale on EdgeOS devices?

Is there anyone that has run this on an EdgeRouter-X?

**Comment by jamesog** [comment]
It's probably better to ask over on the [Tailscale forums](https://forum.tailscale.com/).

I don't have numbers, but I can tell you that on an ER4 there's no performance hit that I can tell.
