### ISSUE TITLE
Seemingly incorrect routing entry inserted

### ISSUE THREAD

**Issue by robbak** [jamesog/tailscale-edgeos#40]
I setup tailscale on my edge device, set up without an exit node because I'm just using it to be able to connect between my computers. It has added two entries in the routing table - `Yes		100.x.y.z/32		tailscale0	connected	Yes`,which is good, that's the router's tailscale ip, but the other is `Yes		0.0.0.0/32		tailscale0	connected	Yes`, which seems wrong. I would expect that route should be '100.0.0.0/8', to allow local systems to access the tailnet.

What can I do to get the correct routing entry added? My searches haven't revealed any flags or arguments to give tailscale this information.

**Comment by jamesog** [comment]
Please open an issue with Tailscale. This repo is just instructions for getting it running on EdgeOS devices, I can't give support for Tailscale itself.
