### ISSUE TITLE
100% CPU usage following reboot on EdgeRouter X

### ISSUE THREAD

**Issue by dsadsa897897r** [jamesog/tailscale-edgeos#5]
Followed the guide on an EdgeRouter X running v2.0.9-hotfix.2 and installed tailscale_1.18.1_mipsle.tgz

All appeared to be fine, but following reboot 'top' showed the CPU as continuously maxed out despite no traffic.

Any idea on what might be causing this?

**Comment by jamesog** [comment]
Hello. I can't provide support for Tailscale I'm afraid, this repo is just an installation guide. I suggest you raise a ticket in tailscale/tailscale or by emailing support@tailscale.com.
