### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by AllenEllis** [jamesog/tailscale-edgeos#6]
When I run `tailscale up` I get this error:

```bash
bash: /usr/sbin/tailscale: cannot execute binary file: Exec format error
```

This is on an EdgeRouter X running the latest firmware. Do I have the wrong platform?

**Comment by jamesog** [comment]
Hey Allen. Yeah, it sounds like the wrong platform version has been installed. I think the ERX uses the MIPS-LE processes, whereas others use MIPS.

Did you install using the package method? If so can you show the output of `sudo apt-get update` so I can see how it's pulling from the repo?

Also useful would be `sudo dpkg --print-architecture` to confirm that it's really `mipsle`.

**Comment by axiomdata** [comment]
I have same router and same error. Here is my output:

Ign:1 http://http.us.debian.org/debian wheezy InRelease
Ign:2 http://http.us.debian.org/debian wheezy Release
Ign:3 http://http.us.debian.org/debian wheezy/main mipsel Packages
Ign:4 http://http.us.debian.org/debian wheezy/main all Packages
Ign:5 http://http.us.debian.org/debian wheezy/main Translation-en
Ign:6 http://http.us.debian.org/debian wheezy/contrib all Packages
Ign:7 http://http.us.debian.org/debian wheezy/contrib mipsel Packages
Ign:9 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy InRelease
Ign:10 http://http.us.debian.org/debian wheezy/contrib Translation-en
Ign:11 http://http.us.debian.org/debian wheezy/non-free mipsel Packages
Ign:12 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy Release
Ign:13 http://http.us.debian.org/debian wheezy/non-free all Packages
Ign:14 http://http.us.debian.org/debian wheezy/non-free Translation-en
Ign:15 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main all Packages
Ign:3 http://http.us.debian.org/debian wheezy/main mipsel Packages
Ign:16 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main mipsel Packages
Ign:4 http://http.us.debian.org/debian wheezy/main all Packages
Ign:5 http://http.us.debian.org/debian wheezy/main Translation-en
Ign:17 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main Translation-en
Ign:6 http://http.us.debian.org/debian wheezy/contrib all Packages
Ign:15 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main all Packages
Ign:7 http://http.us.debian.org/debian wheezy/contrib mipsel Packages
Ign:16 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main mipsel Packages
Ign:10 http://http.us.debian.org/debian wheezy/contrib Translation-en
Ign:11 http://http.us.debian.org/debian wheezy/non-free mipsel Packages
Ign:17 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main Translation-en
Ign:13 http://http.us.debian.org/debian wheezy/non-free all Packages
Ign:15 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main all Packages
Ign:14 http://http.us.debian.org/debian wheezy/non-free Translation-en
Ign:16 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main mipsel Packages
Ign:3 http://http.us.debian.org/debian wheezy/main mipsel Packages
Ign:17 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main Translation-en
Ign:4 http://http.us.debian.org/debian wheezy/main all Packages
Ign:5 http://http.us.debian.org/debian wheezy/main Translation-en
Ign:15 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main all Packages
Ign:6 http://http.us.debian.org/debian wheezy/contrib all Packages
Ign:16 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main mipsel Packages
Ign:7 http://http.us.debian.org/debian wheezy/contrib mipsel Packages
Ign:17 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main Translation-en
Ign:15 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main all Packages
Ign:10 http://http.us.debian.org/debian wheezy/contrib Translation-en
Ign:11 http://http.us.debian.org/debian wheezy/non-free mipsel Packages
Ign:16 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main mipsel Packages
Ign:13 http://http.us.debian.org/debian wheezy/non-free all Packages
Ign:14 http://http.us.debian.org/debian wheezy/non-free Translation-en
Ign:17 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main Translation-en
Ign:3 http://http.us.debian.org/debian wheezy/main mipsel Packages
Ign:4 http://http.us.debian.org/debian wheezy/main all Packages
Ign:15 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main all Packages
Ign:5 http://http.us.debian.org/debian wheezy/main Translation-en
Err:16 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main mipsel Packages
  404  Not Found
Ign:6 http://http.us.debian.org/debian wheezy/contrib all Packages
Ign:17 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy/main Translation-en
Ign:7 http://http.us.debian.org/debian wheezy/contrib mipsel Packages
Ign:10 http://http.us.debian.org/debian wheezy/contrib Translation-en
Ign:11 http://http.us.debian.org/debian wheezy/non-free mipsel Packages
Ign:13 http://http.us.debian.org/debian wheezy/non-free all Packages
Ign:14 http://http.us.debian.org/debian wheezy/non-free Translation-en
Ign:3 http://http.us.debian.org/debian wheezy/main mipsel Packages
Ign:4 http://http.us.debian.org/debian wheezy/main all Packages
Ign:5 http://http.us.debian.org/debian wheezy/main Translation-en
Ign:6 http://http.us.debian.org/debian wheezy/contrib all Packages
Ign:7 http://http.us.debian.org/debian wheezy/contrib mipsel Packages
Ign:10 http://http.us.debian.org/debian wheezy/contrib Translation-en
Ign:11 http://http.us.debian.org/debian wheezy/non-free mipsel Packages
Ign:13 http://http.us.debian.org/debian wheezy/non-free all Packages
Ign:14 http://http.us.debian.org/debian wheezy/non-free Translation-en
Err:3 http://http.us.debian.org/debian wheezy/main mipsel Packages
  404  Not Found [IP: 64.50.233.100 80]
Ign:4 http://http.us.debian.org/debian wheezy/main all Packages
Ign:5 http://http.us.debian.org/debian wheezy/main Translation-en
Ign:6 http://http.us.debian.org/debian wheezy/contrib all Packages
Ign:7 http://http.us.debian.org/debian wheezy/contrib mipsel Packages
Ign:10 http://http.us.debian.org/debian wheezy/contrib Translation-en
Ign:11 http://http.us.debian.org/debian wheezy/non-free mipsel Packages
Ign:13 http://http.us.debian.org/debian wheezy/non-free all Packages
Ign:14 http://http.us.debian.org/debian wheezy/non-free Translation-en
Fetched 5544 B in 6s (890 B/s)
Reading package lists... Done
W: The repository 'http://http.us.debian.org/debian wheezy Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist wheezy Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://http.us.debian.org/debian/dists/wheezy/main/binary-mipsel/Packages  404  Not Found [IP: 64.50.233.100 80]
E: Failed to fetch https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist/dists/wheezy/main/binary-mipsel/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by axiomdata** [comment]
After typing sudo dpkg --print-architecture I got "mipsel"

**Comment by jamesog** [comment]
@axiomdata what version of EdgeOS are you running? Wheezy is very old so I suspect you're on 1.x which is definitely not supported by this setup.

**Comment by axiomdata** [comment]
I'm on 2.0.9.hotfix.2 which is currently the most recent version for of EdgeOS available to (E50).

**Comment by jamesog** [comment]
Alright, maybe the ERX is somehow different, but that's pretty odd that it says wheezy.

@AllenEllis if yours also reports wheezy, I wonder if that's the issue. Either way, I think it confirms you should try raising this as an issue with Tailscale directly. It's either their repo doesn't have `mipsle` binaries for .deb, or something to do with the ERX running wheezy.

**Comment by AllenEllis** [comment]
@jamesog Thanks so much for the response. This particular EdgeRouter I had to provision and then send off-site so I don't have physical access to it any longer. I'll try to setup a remote login with someone there next week and report back.

**Comment by jamesog** [comment]
I haven't heard back on this for some time so I'll close it out. If it's still an issue I'd recommend creating an issue with the Tailscale team to investigate their packages.
